# Generated by Django 4.2.2 on 2023-06-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_app', '0002_booking_price_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_bill',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Итоговый счет'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price_hour',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за час'),
        ),
    ]
