# Generated by Django 4.2.2 on 2023-06-29 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_app', '0003_booking_total_bill_alter_booking_price_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='has_locker_room',
            field=models.BooleanField(default=False, verbose_name='Наличие раздевалки'),
        ),
        migrations.AddField(
            model_name='field',
            name='has_parking',
            field=models.BooleanField(default=False, verbose_name='Наличие парковки'),
        ),
        migrations.AddField(
            model_name='field',
            name='has_shower',
            field=models.BooleanField(default=False, verbose_name='Наличие душа'),
        ),
        migrations.AddField(
            model_name='field',
            name='size_of_field',
            field=models.TextField(max_length=100, null=True, verbose_name='Размер поля'),
        ),
        migrations.AddField(
            model_name='field',
            name='surface_type',
            field=models.CharField(choices=[('газон', 'Газон'), ('паркет', 'Паркет')], default='Газон', max_length=100, verbose_name='Тип покрытия'),
        ),
        migrations.AddField(
            model_name='owner',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='owner',
            name='contact',
            field=models.CharField(default='+996', max_length=100, verbose_name='Контактные данные'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_app.field', verbose_name='Поле'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='field_app.owner', verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='selected_date',
            field=models.DateField(verbose_name='Выбранная дата'),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Поле'),
        ),
        migrations.AlterField(
            model_name='field',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_app.owner', verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя владельца'),
        ),
    ]
