# Generated by Django 4.2.2 on 2023-06-29 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('field_app', '0004_field_has_locker_room_field_has_parking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='size_of_field',
            field=models.CharField(default='Длина:  Ширина: ', max_length=100, verbose_name='Размер поля'),
        ),
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='field_app.owner')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
