# Generated by Django 4.2.2 on 2023-06-30 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('field_app', '0005_alter_field_size_of_field_ownerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='field_app.owner', verbose_name='Владелец'),
        ),
        migrations.DeleteModel(
            name='OwnerProfile',
        ),
    ]
