# Generated by Django 4.2.2 on 2023-06-30 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_app', '0006_owner_user_alter_booking_owner_delete_ownerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='field_app.owner', verbose_name='Владелец'),
        ),
    ]
