# Generated by Django 4.2.2 on 2023-07-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_app', '0007_alter_booking_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='has_roof',
            field=models.BooleanField(default=False, verbose_name='Крытое/Некрытое'),
        ),
    ]
