# Generated by Django 4.2.2 on 2023-07-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_app', '0008_field_has_roof'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='photo',
            field=models.ImageField(default=None, upload_to='fields/'),
        ),
    ]
