# Generated by Django 4.2.2 on 2023-07-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_app', '0009_field_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='fields/'),
        ),
    ]
