# Generated by Django 4.2.2 on 2023-07-06 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_app', '0011_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Начало')),
                ('end_time', models.DateTimeField(verbose_name='Окончание')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Занято')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_app.field', verbose_name='Поле')),
            ],
        ),
    ]
